import type { Metadata } from "next";
import Image from "next/image";
import Link from "next/link";
import { PublicShell } from "@/components/public-shell";
import { HeartIcon, MapPinIcon, PawIcon } from "@/components/icons";
import { adoptablePets } from "@/lib/demo-data";
import { connectToDatabase } from "@/lib/db";
import { AdoptionListing } from "@/lib/models";
import { getSession } from "@/lib/session";

export const metadata: Metadata = { title: "Adopt a pet" };
type PublicPet={id:string;name:string;species:string;breed:string;age:string;gender:string;location:string;health:string;color:string;imageUrl?:string;shelter?:string};

export default async function AdoptPage({ searchParams }: PageProps<"/adopt">) {
  const params = await searchParams;const session=await getSession();let rows:PublicPet[]=[];
  try{await connectToDatabase();const docs=await AdoptionListing.find({status:{$in:["available","pending"]}}).populate("shelterId","name").lean();rows=docs.map((pet)=>{const shelter=pet.shelterId as unknown as {name?:string};const images=Array.isArray(pet.images)?pet.images as {url?:string}[]:[];return{id:String(pet._id),name:String(pet.name),species:String(pet.species),breed:String(pet.breed||"Mixed breed"),age:String(pet.age||"Age not set"),gender:String(pet.gender||"Unknown"),location:String(pet.location||"Location available from shelter"),health:String(pet.healthStatus||"Health status pending"),color:"#d9e9e3",imageUrl:images[0]?.url,shelter:shelter?.name}})}catch{rows=adoptablePets.map((pet)=>({...pet,imageUrl:undefined,shelter:"FurShield partner shelter"}))}
  if(!rows.length)rows=adoptablePets.map((pet)=>({...pet,imageUrl:undefined,shelter:"FurShield partner shelter"}));
  const species = typeof params.species === "string" ? params.species : "All";const query=typeof params.q==="string"?params.q.toLowerCase():"";const location=typeof params.location==="string"?params.location.toLowerCase():"";const sort=typeof params.sort==="string"?params.sort:"name";
  const visible=rows.filter((pet)=>(species==="All"||pet.species===species)&&(!query||`${pet.name} ${pet.breed}`.toLowerCase().includes(query))&&(!location||pet.location.toLowerCase().includes(location))).sort((a,b)=>sort==="age"?Number.parseInt(a.age)-Number.parseInt(b.age):a.name.localeCompare(b.name));
  return <PublicShell><section className="page-hero"><div className="shell"><p className="eyebrow">Shelter adoption</p><h1>Meet someone worth coming home to.</h1><p>Explore profiles maintained by participating shelters, including each animal&apos;s current health and care status.</p></div></section><section className="content-section shell"><form className="directory-tools"><div className="search-field"><input name="q" aria-label="Search adoptable pets by name or breed" defaultValue={typeof params.q==="string"?params.q:""} placeholder="Name or breed"/></div><div className="search-field"><MapPinIcon/><input name="location" aria-label="Filter by location" defaultValue={typeof params.location==="string"?params.location:""} placeholder="Location"/></div><select name="sort" aria-label="Sort adoptable pets" defaultValue={sort}><option value="name">Name</option><option value="age">Age</option></select><button className="button button-primary">Apply</button></form><div className="filter-bar">{["All","Dog","Cat","Bird"].map((item) => <Link className={`filter-chip ${species === item ? "active" : ""}`} href={item === "All" ? "/adopt" : `/adopt?species=${item}`} key={item}>{item}</Link>)}</div><div className="card-grid">{visible.map((pet) => <article className="catalog-card" id={pet.id} key={pet.id}><div className="catalog-art" style={{background:pet.color}}>{pet.imageUrl?<Image src={pet.imageUrl} alt={`${pet.name}, adoptable ${pet.species}`} width={420} height={280} unoptimized/>:<PawIcon size={58}/>}</div><div className="catalog-body"><div className="meta-row"><span>{pet.species} · {pet.gender}</span><span className="health-label">{pet.health}</span></div><h2>{pet.name}</h2><p>{pet.breed} · {pet.age}</p><p className="location-line"><MapPinIcon /> {pet.location}</p><small>Listed by {pet.shelter}</small><Link className="button button-primary" href={session?.role==="owner"?"/dashboard/adoption":`/register?intent=adopt&pet=${pet.id}`}>I&apos;m interested <HeartIcon /></Link></div></article>)}</div>{!visible.length?<div className="empty-note">No adoptable pets match these filters.</div>:null}</section></PublicShell>;
}
