"use client";

import { useActionState, useState } from "react";
import Link from "next/link";
import { login, register, type AuthState } from "@/app/actions/auth";
import { ArrowIcon } from "./icons";

const initialState:AuthState=undefined;

export function LoginForm(){
  const[state,action,pending]=useActionState(login,initialState);
  const error=(name:string)=>state?.fieldErrors?.[name]?.[0];
  return <form className="auth-form" action={action} noValidate><div className="field"><label htmlFor="email">Email address</label><input id="email" name="email" type="email" autoComplete="email" aria-invalid={Boolean(error("email"))}/>{error("email")?<small className="field-error" role="alert">{error("email")}</small>:null}</div><div className="field"><label htmlFor="password">Password</label><input id="password" name="password" type="password" autoComplete="current-password" aria-invalid={Boolean(error("password"))}/>{error("password")?<small className="field-error" role="alert">{error("password")}</small>:null}</div>{state?.error?<p className="form-error" role="alert">{state.error}</p>:null}<button className="button button-primary" disabled={pending}>{pending?"Signing in…":<>Log in <ArrowIcon/></>}</button><p className="form-switch">New to FurShield? <Link href="/register">Create an account</Link></p></form>;
}

export function RegisterForm(){
  const[role,setRole]=useState("owner");
  const[state,action,pending]=useActionState(register,initialState);
  const error=(name:string)=>state?.fieldErrors?.[name]?.[0];
  return <form className="auth-form" action={action} noValidate><fieldset><legend>I&apos;m joining as</legend><div className="role-grid">{[["owner","Pet owner"],["vet","Veterinarian"],["shelter","Animal shelter"]].map(([value,label])=><label className="role-option" key={value}><input type="radio" name="role" value={value} checked={role===value} onChange={()=>setRole(value)}/><span>{label}</span></label>)}</div></fieldset>{role==="shelter"?<div className="field"><label htmlFor="shelterName">Shelter name</label><input id="shelterName" name="shelterName" aria-invalid={Boolean(error("shelterName"))}/>{error("shelterName")?<small className="field-error" role="alert">{error("shelterName")}</small>:null}</div>:null}<div className="field"><label htmlFor="name">{role==="shelter"?"Contact person":"Full name"}</label><input id="name" name="name" autoComplete="name" aria-invalid={Boolean(error("name"))}/>{error("name")?<small className="field-error" role="alert">{error("name")}</small>:null}</div>{role==="vet"?<div className="field"><label htmlFor="specialization">Specializations</label><input id="specialization" name="specialization" placeholder="e.g. small animal medicine, dermatology"/></div>:null}<div className="field"><label htmlFor="reg-email">Email address</label><input id="reg-email" name="email" type="email" autoComplete="email" aria-invalid={Boolean(error("email"))}/>{error("email")?<small className="field-error" role="alert">{error("email")}</small>:null}</div><div className="field"><label htmlFor="phone">Contact number</label><input id="phone" name="phone" type="tel" autoComplete="tel" aria-invalid={Boolean(error("phone"))}/>{error("phone")?<small className="field-error" role="alert">{error("phone")}</small>:null}</div><div className="field"><label htmlFor="address">Address</label><textarea id="address" name="address" autoComplete="street-address" aria-invalid={Boolean(error("address"))}/>{error("address")?<small className="field-error" role="alert">{error("address")}</small>:null}</div><div className="field"><label htmlFor="reg-password">Password</label><input id="reg-password" name="password" type="password" autoComplete="new-password" aria-invalid={Boolean(error("password"))}/><small>Use at least 8 characters.</small>{error("password")?<small className="field-error" role="alert">{error("password")}</small>:null}</div>{state?.error?<p className="form-error" role="alert">{state.error}</p>:null}<button className="button button-primary" disabled={pending}>{pending?"Creating your space…":<>Create account <ArrowIcon/></>}</button><p className="form-switch">Already have an account? <Link href="/login">Log in</Link></p></form>;
}
